
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
#      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB


#file
# dir: C:\\upload