
spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
#     ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100



  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ssu-rental-bucket
    stack:
      auto: false
    credentials:
      access-key: ${LOCAL_ACCESS_KEY}
      secret-key: ${LOCAL_SECRET_KEY}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


