
spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://ssurentaldb.ccny9xairkls.ap-northeast-2.rds.amazonaws.com:3306/ssu_rental_db
    username: admin
    password: ssurental01
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
#     ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ssu-rental-bucket
    stack:
      auto: false
    credentials:
      access-key: AKIATLEO2CZ4VTPQB4W7
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error



